version: '3'

services:
  mysql:
    image: 'mysql:latest'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 9910:3306
    environment:
      - MYSQL_USER=grimoire
      - MYSQL_DATABASE=grimoire_test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  postgres:
    image: 'postgres:alpine'
    ports:
      - 9920:5432
    environment:
      - POSTGRES_USER=grimoire
      - POSTGRES_DB=grimoire_test
